---
- name: terragrunt
  tags: terragrunt
  include_role:
    name: install
  vars:
    install_name: terragrunt
    install_version: "0.18.3"
    install_url: https://github.com/gruntwork-io/terragrunt/releases/download/v{{ install_version }}/terragrunt_linux_amd64
    install_tests: []
    install_binaries:
      - src: terragrunt_linux_amd64
        dest: terragrunt
