---
- name: helmfile
  tags: helmfile
  include_role:
    name: install
  vars:
    install_name: helmfile
    install_version: "0.67.0"
    install_url: "https://github.com/roboll/{{ install_name }}/releases/download/v{{ install_version }}/{{ install_name }}_linux_amd64"
    install_tests:
      - command: "helmfile --version"
        result: "{{ install_name }} version v{{ install_version }}"
    install_binaries:
      - src: "{{ install_name }}_linux_amd64"
        dest: "{{ install_name }}"
