---
install_cache_dir: "{{ ansible_env.HOME + '/.cache/install' }}"
install_dest_dir: ~/bin
install_tasks: []
install_binaries: []
install_uncompress_extensions:
  - .gz
install_unarchive_enabled: true
install_archive_regex: '\.(rar|zip|tgz|tar(|\.(gz|bz2|xz)))$'
install_archive_extensions:
  - tgz
  - tar.gz
  - tar.bz2
  - tar.xz
  - zip
  - rar
