---
- name: cfssljson
  tags: cfssljson
  include_role:
    name: install
  vars:
    install_unarchive_enabled: false
    install_name: cfssljson
    install_version: "1.2"
    install_url: https://pkg.cfssl.org/R{{ install_version }}/cfssljson_linux-amd64
    install_tests: []
    install_binaries:
      - src: cfssljson_linux-amd64
        dest: cfssljson
