---
- name: helm
  tags: helm
  include_role:
    name: install
  vars:
    install_version: v2.13.1
    install_url: >
      https://storage.googleapis.com/kubernetes-helm/helm-{{ install_version }}-linux-amd64.tar.gz
    install_binaries:
      - linux-amd64/helm
      - linux-amd64/tiller
    install_tests:
      - command: helm version --client --short
        result: "Client: {{ install_version }}+"
      - command: tiller -version
        result: "{{ install_version }}"
